### ISSUE TITLE
ExtrenalLinkhs fuer mehrsprachige dokumente

### ISSUE THREAD

**Issue by jvoigt** [bringbackourneighbours/bringbackourneighbours#125]
z.B. https://sab.landtag.sachsen.de/download/SAB/SAB-HfK_11sprachig_3-2023_web.pdf

Das soll dann so angelegt werden können:

```
all:  
  slug: hfk  
  url: [https://sab.landtag.sachsen.de/download/SAB/SAB-HfK_11sprachig_3-2023_web.pdf](https://sab.landtag.sachsen.de/download/SAB/SAB-HfK_11sprachig_3-2023_web.pdf%EF%BF%BC)  
  type: WEB  
en:  
  title: 'SAXON COMMISSION ON HARDSHIP CASES'  
de:  
  title: 'SÄCHSISCHE HÄRTEFALLKOMMISSION Aufenthaltsrecht aus humanitären Gründen'
```
