### ISSUE TITLE
Content: check link slugs for length and collitions

### ISSUE THREAD

**Issue by jvoigt** [bringbackourneighbours/bringbackourneighbours#477]
many of the link slugs are quiet long `w2eu-deportationde` could the shorted... but we need to make sure there are no collisions

**Comment by jvoigt** [comment]
i actually found one collision:
https://github.com/bringbackourneighbours/bringbackourneighbours/commit/936aa242a21f4afaa0f39545d6e09f6faf17576b#diff-5e254d866a527c25404b01e82cb9e259c6a4f3ae2248ba13cc4eca99cbc498cfR20

in the link "tapping" there was the same slug used twice. It would have been nice to catch such easily detectable bugs.

it was like:

```yaml
de:
  slug: tappingde
  title: Selbsthilfe bei Trauma mit der Trauma Tapping Technik
  type: PDF
  url: https://www.selfhelpfortrauma.org/s/TTT_StepByStep-German.pdf
en:
  slug: tappingde
  title: Self-help for trauma with the Trauma Tapping Technique
  type: PDF
  url: https://www.selfhelpfortrauma.org/s/TTT_StepBySteppdf.zip
es:
  slug: tappinges
  title: Autoayuda para traumas con la técnica de tapping para traumas
  type: PDF
  url: https://www.selfhelpfortrauma.org/s/TTT_StepByStep-Spain.pdf
```
